version: '3.8'
services:
  churn_model_app:
    build: .
    ports:
      - "5001:5001"
    container_name: churn_model_app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana
    environment: 
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=rickmike330@gmail.com 
      - GF_SMTP_PASSWORD=ufmb xoib drhk phfw 
      - GF_SMTP_FROM_ADDRESS=grafana@yourdomain.com 
      - GF_SMTP_FROM_NAME=Grafana Churn Alerts 
      - GF_SMTP_SKIP_VERIFY=false 
      - GF_PATHS_DATA=/var/lib/grafana
    volumes: 
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data: