slang_dict = {
    "abis": "habis",
    "ad": "ada",
    "adek": "adik", "adik": "adik",
    "aj": "saja", "aja": "saja",
    "ak": "aku",
    "ama": "sama",
    "ampe": "sampai",
    "anakanak": "anak-anak",
    "anj": "anjir", "anjir": "anjir",
    "ap": "apa",
    "apdate": "update", "apdet": "update",
    "apk": "aplikasi", "aplikasi": "aplikasi", "aplikasinya": "aplikasi", "app": "aplikasi",
    "apus": "hapus", "hapu": "hapus",
    "asalamualaikum": "Assalamualaikum", "assalamualaikum": "Assalamualaikum",
    "asyik": "asik",
    "ato": "atau",
    "baget": "banget",
    "bagu": "bagus", "bagus": "bagus", "baguss": "bagus", "bagusss": "bagus", "bagussss": "bagus", "bagusssss": "bagus", "bagussssss": "bagus", "bagusssssss": "bagus",
    "bagustapi": "bagus tapi",
    "baju": "baju", "bajunya": "baju",
    "bang": "bang",
    "bangat": "banget", "banget": "banget", "bangetapa": "banget", "bangett": "banget", "bangettapi": "banget tapi",
    "bangettt": "banget", "bangetttt": "banget", "bangettttt": "banget", "bangetttttt": "banget", "bangettttttt": "banget", "bangetttttttt": "banget", "bangetttttttttt": "banget", "bangt": "banget",
    "bangus": "bagus",
    "bantu": "bantu", "bantuannya": "bantu",
    "banyakin": "banyak",
    "barang": "barang", "barangnya": "barang",
    "bareng": "bersama",
    "bat": "banget",
    "bay": "bye",
    "belom": "belum",
    "bener": "benar", "beneran": "benar",
    "benerin": "perbaiki",
    "benget": "banget",
    "bestie": "sahabat",
    "bgs": "bagus",
    "bgt": "banget", "bgtt": "banget", "bgttt": "banget",
    "bgus": "bagus",
    "bintang": "bintang", "bintangnya": "bintang",
    "blm": "belum",
    "bnget": "banget", "bngt": "banget",
    "bnyak": "banyak", "bnyk": "banyak",
    "bocil": "anak kecil",
    "bohong": "bohong", "boong": "bohong",
    "bosan": "bosan", "bosen": "bosan",
    "bs": "bisa", "bsa": "bisa",
    "btw": "ngomong-ngomong",
    "bug": "bug", "bugnya": "bug",
    "burik": "buruk",
    "buruan": "buru",
    "bye": "bye", "byee": "bye",
    "byk": "banyak",
    "cape": "capek", "capek": "capek",
    "cepet": "cepat", "cepetan": "cepat",
    "cmn": "hanya",
    "coba": "coba", "cobain": "coba",
    "cuman": "cuma",
    "dada": "bye", "dadah": "bye",
    "dapet": "dapat", "dapetin": "dapat",
    "dekor": "dekorasi",
    "dev": "developer", "developer": "developer", "developernya": "developer",
    "dgn": "dengan",
    "dh": "sudah",
    "dibaca": "baca",
    "dibenerin": "perbaiki",
    "dibilang": "bilang",
    "dibuka": "buka",
    "dicoba": "coba",
    "didownload": "download",
    "dihapus": "hapus",
    "dijamin": "jamin",
    "dikasih": "kasih",
    "dikit": "sedikit",
    "dikurangi": "kurangi", "dikurangin": "kurangi",
    "dimainin": "main", "dimainkan": "main",
    "dimana": "di mana",
    "diperbaiki": "perbaiki",
    "diperbarui": "perbarui",
    "dirumah": "rumah",
    "disuruh": "suruh",
    "ditambah": "tambah", "ditambahin": "tambah",
    "diturunin": "turun",
    "diupdate": "perbarui",
    "dlu": "dulu",
    "dm": "diamond",
    "dolnot": "download", "donglod": "download", "donglot": "download",
    "donload": "download", "donlod": "download", "donlot": "download", "donlowd": "download", "donwload": "download", "dowload": "download", "dowlod": "download", "dowlot": "download", "download": "download", "downloadnya": "download", "downlod": "download",
    "dpt": "dapat",
    "dri": "dari",
    "duit": "uang", "duitnya": "uang",
    "dwonload": "download",
    "emang": "memang",
    "engak": "tidak", "engga": "tidak",
    "eror": "error", "error": "error",
    "g": "tidak", "ga": "tidak",
    "gaada": "tidak ada",
    "gabisa": "tidak bisa",
    "gacha": "gatcha",
    "gais": "guys",
    "gajelas": "tidak jelas",
    "gak": "tidak",
    "game": "game", "gamee": "game", "gameny": "game", "gamenya": "game", "games": "game", "gane": "game",
    "gapapa": "tidak apa-apa",
    "gatau": "tidak tahu",
    "gays": "guys",
    "gede": "besar",
    "gem": "diamond", "gema": "game", "gemanya": "game", "geme": "game", "gemenya": "game", "gemes": "game", "gemnya": "game", "gems": "game", "gemya": "game",
    "gimana": "bagaimana",
    "gitu": "begitu", "gituu": "begitu", "gt": "begitu", "gtu": "begitu",
    "gk": "tidak", "gb": "gigabyte",
    "gm": "bagaimana", "gmn": "bagaimana",
    "good": "bagus",
    "gpp": "tidak apa-apa",
    "grafik": "grafik", "grafiknya": "grafik",
    "gua": "saya", "gue": "saya", "gw": "saya",
    "hilang": "hilang", "ilang": "hilang",
    "hape": "handphone", "hp": "handphone", "hpku": "handphone", "hpnya": "handphone",
    "hegin": "haegin",
    "iklan": "iklan", "iklannya": "iklan",
    "kangen": "kangen",
    "kasi": "kasih", "ksih": "kasih",
    "kaya": "seperti", "kayak": "seperti", "kayaknya": "seperti",
    "kehapus": "hapus",
    "kemaren": "kemarin", "kemarin": "kemarin",
    "kembalikan": "kembali",
    "kesel": "kesal",
    "klian": "kalian",
    "kluar": "keluar",
    "knp": "kenapa",
    "komen": "komentar", "komentar": "komentar",
    "krn": "karena", "krna": "karena",
    "kyk": "seperti",
    "lagii": "lagi",
    "lg": "lagi",
    "lambat": "lag",
    "leg": "lag",
    "liat": "lihat", "liatliat": "lihat", "liat²": "lihat", "lihat": "lihat",
    "like": "suka",
    "loading": "loading", "loadingnya": "loading", "loding": "loading",
    "loncat": "lompat",
    "love": "suka",
    "lu": "kamu",
    "mabar": "main bareng",
    "maen": "main",
    "mahal²": "mahal",
    "mainin": "main", "mainkan": "main", "mainnya": "main", "mainan": "main", "mainannya": "main",
    "makasi": "terima kasih", "makasih": "terima kasih",
    "malem": "malam",
    "males": "malas",
    "masi": "masih",
    "mb": "megabyte", "mbnya": "megabyte",
    "memo": "memori", "memori": "memori", "memorinya": "memori", "memory": "memori",
    "min": "",
    "mo": "mau",
    "moga": "semoga",
    "mulu": "mulu",
    "murahin": "murah",
    "nambah": "tambah",
    "nanya": "tanya",
    "napa": "kenapa",
    "ngabisin": "habis",
    "ngak": "tidak", "ngga": "tidak", "nggak": "tidak", "ngk": "tidak",
    "ngapain": "ngapain",
    "ngasih": "kasih",
    "ngebak": "bug",
    "ngebosenin": "bosan",
    "ngebug": "bug",
    "ngelag": "lag", "ngeleg": "lag", "ngelek": "lag",
    "ngeselin": "kesal",
    "ngestuck": "stuck",
    "ngetik": "ketik",
    "nyari": "cari",
    "nyesal": "kesal", "nyesel": "kesal",
    "nyoba": "coba",
    "obby": "obby",
    "ok": "oke", "oke": "oke",
    "org": "orang", "orng": "orang",
    "pake": "pakai", "pakek": "pakai", "pale": "pakai",
    "pancing": "pancingan", "pancingan": "pancingan",
    "parkour": "parkour", "parkur": "parkour",
    "pdhl": "padahal",
    "plis": "please", "pliss": "please", "plisss": "please", "pls": "please", "please": "tolong",
    "poko": "intinya", "pokok": "intinya", "pokoknya": "intinya", "pokonya": "intinya",
    "pt": "play together",
    "playtogether": "play together",
    "quest": "misi",
    "rame": "ramai",
    "rate": "rating", "rating": "rating",
    "rumahnya": "rumah",
    "sampe": "sampai", "sampek": "sampai",
    "saranin": "saran",
    "sayang": "sayang", "sayangnya": "sayang",
    "sdh": "sudah",
    "sebenernya": "sebenarnya",
    "seneng": "senang",
    "serubanget": "seru banget",
    "seruh": "seru", "serunya": "seru", "seruu": "seru", "seruuu": "seru", "seruuuu": "seru", "seruuuuu": "seru", "seruuuuuu": "seru",
    "server": "seru", "servernya": "seru",
    "skrg": "sekarang", "skrng": "sekarang",
    "slalu": "selalu",
    "sm": "sama", "sma": "sama",
    "sorry": "maaf",
    "star": "bintang",
    "store": "toko",
    "suka": "suka", "sukaa": "suka", "sukaaa": "suka", "sukai": "suka",
    "sy": "saya", "sya": "saya",
    "tambahin": "tambah", "tambahan": "tambah", "tambahkan": "tambah",
    "tapii": "tapi",
    "tau": "tahu",
    "tdk": "tidak",
    "temen": "teman", "teman": "teman", "temanku": "teman", "temanteman": "teman", "temenan": "teman",
    "terimakasih": "terima kasih", "trimakasih": "terima kasih", "thanks": "terima kasih", "thank": "terima kasih",
    "teruss": "terus",
    "tetep": "tetap", "ttp": "tetap",
    "tibatiba": "tiba-tiba", "tiba²": "tiba-tiba",
    "tmn": "teman",
    "tp": "tapi", "tpi": "tapi",
    "trs": "terus", "trus": "terus",
    "tu": "", "tuh": "",
    "tulisan": "tulisan", "tulisannya": "tulisan",
    "turunin": "turun", "turunkan": "turun",
    "uang": "uang", "uangnya": "uang",
    "ubah": "rubah",
    "uda": "sudah", "udah": "sudah", "udh": "sudah",
    "unduh": "download", "unduhan": "download",
    "uninstal": "uninstall", "uninstall": "uninstall",
    "update": "update", "updatean": "update", "updatenya": "update", "updet": "update", "updete": "update", "upgrade": "update",
    "utk": "untuk",
    "wifi": "Wi-Fi",
    "wih": "wow", "waw": "wow",
    "zem": "zem", "zepeto": "zepeto",
    "zombi": "zombie", "zombie": "zombie",
    "jga": "juga", "nih": "",
    "bagusseru": "bagus seru", "ads": "iklan", "ngelagggggg": "lag", "yah": "", "kak": "",
    "oke":"","Oke": "", "ni":"", "biar":"", "klo":"", "pk xd": "",
    "nya": "", "yg": "", "si": "", "deh": "", "oh": "", "mulu": "", "kali": "", "ny": ""
}